### ISSUE TITLE
Video cannot be played back

### ISSUE THREAD

**Issue by lrmw** [benjamin-maynard/Pi-Camera-in-a-box#5]
Hi Benjamin,

first of all, thank you very much for this repository, I learned a lot from this complex-yet-still-simple real world docker & compose application!

However, I don't seem to be able to receive video - neither from the UI nor if I open the m3mu directly in VLC. The UI just says "The media could not be loaded, either because the server or network failed or because the format is not supported." and VLC (when given the correct auth info) says:

> main debug: connecting to 192.168.178.31 port 80 ...
> main debug: creating demux: access='' demux='ts' location='' file='(null)'
> main debug: looking for demux module matching "ts": 55 candidates
> adaptive error: Failed reading http://192.168.178.31:80/hls/stream-0.ts: HTTP/1.1 401 Unauthorized
> main debug: no demux modules matched
> adaptive error: Failed to create demuxer 00000000 TS
> main debug: EOF reached

Do you have an idea about what could be happening?

Thank you very much!
Milan

**Comment by benjamin-maynard** [comment]
Hey Milan,

Couple of things:

1. Can you send me the output of `docker-compose logs` from the directory you have cloned Pi-Camera-in-a-box to?
2. Have you edited any of the environment variables in the .env file?

**Comment by lrmw** [comment]
Hi Benjamin,

sorry for the delay. I just restarted everything and tried to get the logs. Since the logs were huge I deleted them and started the containers again. Funnily enough, it worked for a few minutes and displayed the image (although with almost 45s delay). Then the Pi Zero hung up and I had to restart again. After this, I again cannot get it to work, I'm beginning to think the Pi Zero might be a little too slow.

However, I managed to pull the following logs:

> Attaching to pi-camera-in-a-box_ffmpeg_1, pi-camera-in-a-box_nginx-rtsp_1
> ffmpeg_1      | ffmpeg version N-91345-gb86c575 Copyright (c) 2000-2018 the FFmpeg developers
> nginx-rtsp_1  | /entrypoint.sh: line 14: Add: command not found
> nginx-rtsp_1  | /entrypoint.sh: line 14: Add: command not found
> ffmpeg_1      |   built with gcc 4.9.2 (Raspbian 4.9.2-10+deb8u1)
> ffmpeg_1      |   configuration: --enable-cross-compile --cross-prefix= --arch=armel --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree
> ffmpeg_1      |   libavutil      56. 18.102 / 56. 18.102
> ffmpeg_1      |   libavcodec     58. 20.103 / 58. 20.103
> ffmpeg_1      |   libavformat    58. 17.101 / 58. 17.101
> ffmpeg_1      |   libavdevice    58.  4.101 / 58.  4.101
> ffmpeg_1      |   libavfilter     7. 25.100 /  7. 25.100
> ffmpeg_1      |   libswscale      5.  2.100 /  5.  2.100
> ffmpeg_1      |   libswresample   3.  2.100 /  3.  2.100
> ffmpeg_1      |   libpostproc    55.  2.100 / 55.  2.100
> ffmpeg_1      | Guessed Channel Layout for Input Stream #0.0 : stereo
> ffmpeg_1      | Input #0, s16le, from '/dev/zero':
> ffmpeg_1      |   Duration: N/A, bitrate: 1411 kb/s
> ffmpeg_1      |     Stream #0:0: Audio: pcm_s16le, 44100 Hz, stereo, s16, 1411 kb/s
> ffmpeg_1      | Input #1, h264, from 'pipe:':
> ffmpeg_1      |   Duration: N/A, bitrate: N/A
> ffmpeg_1      |     Stream #1:0: Video: h264 (High), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 1200k tbn, 50 tbc
> ffmpeg_1      | Stream mapping:
> ffmpeg_1      |   Stream #1:0 -> #0:0 (copy)
> ffmpeg_1      |   Stream #0:0 -> #0:1 (pcm_s16le (native) -> aac (native))
> ffmpeg_1      | Output #0, flv, to 'rtmp://nginx-rtsp/show/stream':
> ffmpeg_1      |   Metadata:
> ffmpeg_1      |     encoder         : Lavf58.17.101
> ffmpeg_1      |     Stream #0:0: Video: h264 (High) ([7][0][0][0] / 0x0007), yuv420p(progressive), 1920x1080, q=2-31, 25 fps, 25 tbr, 1k tbn, 1200k tbc
> ffmpeg_1      |     Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 128 kb/s
> ffmpeg_1      |     Metadata:
> ffmpeg_1      |       encoder         : Lavc58.20.103 aac
> ffmpeg_1      | [h264 @ 0x1931b80] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
> ffmpeg_1      | [flv @ 0x1933e40] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
> /entrypoint.sh: line 18:     7 Broken pipe             raspivid -o - -t 0 -fps $FRAMES_PER_SECOND -b $STREAM_BITRATE -w $STREAM_WIDTH -h $STREAM_HEIGHT $HF $VF
> ffmpeg_1      |          8 Segmentation fault      (core dumped) | ffmpeg -re -ar 44100 -ac 2 -acodec pcm_s16le -f s16le -ac 2 -i /dev/zero -f h264 -i - -vcodec copy -acodec aac -ab 128k -g 50 -strict experimental -framerate $FRAMES_PER_SECOND -f flv rtmp://nginx-rtsp/show/stream
> ffmpeg_1      | ffmpeg version N-91345-gb86c575 Copyright (c) 2000-2018 the FFmpeg developers
> ffmpeg_1      |   built with gcc 4.9.2 (Raspbian 4.9.2-10+deb8u1)
> ffmpeg_1      |   configuration: --enable-cross-compile --cross-prefix= --arch=armel --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree
> ffmpeg_1      |   libavutil      56. 18.102 / 56. 18.102
> ffmpeg_1      |   libavcodec     58. 20.103 / 58. 20.103
> ffmpeg_1      |   libavformat    58. 17.101 / 58. 17.101
> ffmpeg_1      |   libavdevice    58.  4.101 / 58.  4.101
> ffmpeg_1      |   libavfilter     7. 25.100 /  7. 25.100
> ffmpeg_1      |   libswscale      5.  2.100 /  5.  2.100
> ffmpeg_1      |   libswresample   3.  2.100 /  3.  2.100
> ffmpeg_1      |   libpostproc    55.  2.100 / 55.  2.100
> ffmpeg_1      | Guessed Channel Layout for Input Stream #0.0 : stereo
> ffmpeg_1      | Input #0, s16le, from '/dev/zero':
> ffmpeg_1      |   Duration: N/A, bitrate: 1411 kb/s
> ffmpeg_1      |     Stream #0:0: Audio: pcm_s16le, 44100 Hz, stereo, s16, 1411 kb/s
> ffmpeg_1      | Input #1, h264, from 'pipe:':
> ffmpeg_1      |   Duration: N/A, bitrate: N/A
> ffmpeg_1      |     Stream #1:0: Video: h264 (High), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 1200k tbn, 50 tbc
> ffmpeg_1      | Stream mapping:
> ffmpeg_1      |   Stream #1:0 -> #0:0 (copy)
> ffmpeg_1      |   Stream #0:0 -> #0:1 (pcm_s16le (native) -> aac (native))
> ffmpeg_1      | Output #0, flv, to 'rtmp://nginx-rtsp/show/stream':
> ffmpeg_1      |   Metadata:
> ffmpeg_1      |     encoder         : Lavf58.17.101
> ffmpeg_1      |     Stream #0:0: Video: h264 (High) ([7][0][0][0] / 0x0007), yuv420p(progressive), 1920x1080, q=2-31, 25 fps, 25 tbr, 1k tbn, 1200k tbc
> ffmpeg_1      |     Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 128 kb/s
> ffmpeg_1      |     Metadata:
> ffmpeg_1      |       encoder         : Lavc58.20.103 aac
> ffmpeg_1      | [h264 @ 0x17d7b80] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
> ffmpeg_1      | [flv @ 0x17db010] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
> ffmpeg_1      | ffmpeg version N-91345-gb86c575 Copyright (c) 2000-2018 the FFmpeg developers
> ffmpeg_1      |   built with gcc 4.9.2 (Raspbian 4.9.2-10+deb8u1)
> ffmpeg_1      |   configuration: --enable-cross-compile --cross-prefix= --arch=armel --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree
> ffmpeg_1      |   libavutil      56. 18.102 / 56. 18.102
> ffmpeg_1      |   libavcodec     58. 20.103 / 58. 20.103
> ffmpeg_1      |   libavformat    58. 17.101 / 58. 17.101
> ffmpeg_1      |   libavdevice    58.  4.101 / 58.  4.101
> ffmpeg_1      |   libavfilter     7. 25.100 /  7. 25.100
> ffmpeg_1      |   libswscale      5.  2.100 /  5.  2.100
> ffmpeg_1      |   libswresample   3.  2.100 /  3.  2.100
> ffmpeg_1      |   libpostproc    55.  2.100 / 55.  2.100
> ffmpeg_1      | Guessed Channel Layout for Input Stream #0.0 : stereo
> ffmpeg_1      | Input #0, s16le, from '/dev/zero':
> ffmpeg_1      |   Duration: N/A, bitrate: 1411 kb/s
> ffmpeg_1      |     Stream #0:0: Audio: pcm_s16le, 44100 Hz, stereo, s16, 1411 kb/s
> ffmpeg_1      | Input #1, h264, from 'pipe:':
> ffmpeg_1      |   Duration: N/A, bitrate: N/A
> ffmpeg_1      |     Stream #1:0: Video: h264 (High), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 1200k tbn, 50 tbc
> ffmpeg_1      | Stream mapping:
> ffmpeg_1      |   Stream #1:0 -> #0:0 (copy)
> ffmpeg_1      |   Stream #0:0 -> #0:1 (pcm_s16le (native) -> aac (native))
> ffmpeg_1      | Output #0, flv, to 'rtmp://nginx-rtsp/show/stream':
> ffmpeg_1      |   Metadata:
> ffmpeg_1      |     encoder         : Lavf58.17.101
> ffmpeg_1      |     Stream #0:0: Video: h264 (High) ([7][0][0][0] / 0x0007), yuv420p(progressive), 1920x1080, q=2-31, 25 fps, 25 tbr, 1k tbn, 1200k tbc
> ffmpeg_1      |     Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 128 kb/s
> ffmpeg_1      |     Metadata:
> ffmpeg_1      |       encoder         : Lavc58.20.103 aac
> ffmpeg_1      | [h264 @ 0x353db80] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
> ffmpeg_1      | [flv @ 0x353f870] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly


The segfault of raspivid is interesting. I had problems with the latest docker from the Raspian/Debian repos, it also segfaulted on my Pi Zero W. I had to revert to 18.06.1-ce to get it to work (see https://github.com/moby/moby/issues/38175). Maybe the segfault here has something to do with that.

I haven't edited the config file other than changing the authentication info.

Thanks!

**Comment by benjamin-maynard** [comment]
@milancpp - Apologies it took me so long to get back on this. I didn't get a notification and have only just noticed your replied.

I can't see anything immediate in the logs that points me to a root cause, the Segmentation Fault is interesting but not sure what is causing it.

Are you running anything else on the Pi that is resource intensive? Did you build the Docker images yourself or pull them from Docker Hub? Just trying to understand if anything deviates from a standard configuration.
